export default function TermsPage() {
  return (
    <section className="bg-creta px-5 py-[60px] md:px-12 md:py-20">
      <div className="mx-auto max-w-[720px]">
        <h1 className="font-display text-[40px] text-umbra">Terms of Use</h1>
        <p className="mt-3 text-[13px] text-pizarra">Last updated: April 21, 2026</p>
        <hr className="mb-10 mt-6 border-[rgba(44,40,37,0.1)]" />

        <div className="space-y-6 text-[15px] leading-[1.7] text-umbra">
          <p>
            Please read these Terms of Use ("Terms") carefully before using the peri iOS
            application ("the App"), developed by Dysbert Tovar ("we," "our," or "us"). By
            downloading or using the App, you agree to be bound by these Terms.
          </p>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the App, you confirm that you are at least 18 years old and
              agree to these Terms. If you do not agree, do not use the App.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">2. Description of Service</h2>
            <p>
              peri is a symptom-tracking application designed to help users record and review
              perimenopause-related symptoms. The App is a personal logging tool. It does not
              provide medical advice, diagnosis, or treatment.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">3. Not Medical Advice</h2>
            <p>
              The information and data generated by the App — including symptom logs, charts, and
              PDF reports — are for personal informational purposes only. Nothing in the App
              constitutes medical advice. Always consult a qualified healthcare professional for
              medical decisions. Do not delay or disregard professional medical advice based on
              information from the App.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">4. User Responsibilities</h2>
            <p>
              You are responsible for the accuracy of the data you enter. You agree not to use the
              App for any unlawful purpose. You agree not to attempt to reverse-engineer, modify,
              or redistribute the App.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">5. Subscriptions and Purchases</h2>
            <p>
              The App offers optional in-app subscriptions for premium features. Subscriptions are
              billed through your Apple ID. You can manage or cancel your subscription at any time
              through your Apple ID account settings. No refunds are provided for partial
              subscription periods except as required by applicable law.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">6. Intellectual Property</h2>
            <p>
              All content, design, code, and branding in the App are owned by Dysbert Tovar and
              protected by applicable intellectual property laws. You may not reproduce or
              distribute any part of the App without written permission.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">7. Disclaimer of Warranties</h2>
            <p>
              The App is provided "as is" without warranties of any kind, express or implied. We
              do not warrant that the App will be error-free, uninterrupted, or free of bugs. We
              are not responsible for any data loss resulting from device failure or App errors.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Dysbert Tovar shall not be liable for any
              indirect, incidental, special, or consequential damages arising from your use of the
              App, including but not limited to loss of data or health decisions made based on App
              content.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">9. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. The updated date at the top of this page will
              reflect changes. Continued use of the App after changes constitutes acceptance of the
              updated Terms.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">10. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the jurisdiction in which the developer
              resides, without regard to conflict-of-law principles.
            </p>
          </section>

          <section>
            <h2 className="mt-10 text-[18px] font-semibold">11. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{" "}
              <a className="text-siena hover:underline" href="mailto:dysbert@gmail.com">
                dysbert@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </section>
  );
}
